### ISSUE TITLE
Errors with the Sontag solver

### ISSUE THREAD

**Issue by almeida85** [Hoecker-Lab/pocketoptimizer#7]
Hello,

I have been using PocketOptimizer for my system for the last couple of weeks and sometimes I get these errors:

```
python /media/Data1/Softwares/pocketoptimizer/pocketoptimizer/ui.py -ff charmm36 -r receptor.pdb -l ligand.mol2 --ph 7 --min_bb --mutations A:111:ALL A:132:ALL A:344:ALL A:374:ALL A:376:ALL --library dunbrack --accurate --include_native --nconfs 200 --trans 5 --scoring vina --ncpus 8 --num_solutions 10
.
.
.
2023-10-17 11:23:30,487 - pocketoptimizer.scoring.smina_scorer - INFO - Ligand-Sidechain interaction energy for residue: A_376_THR already computed.
2023-10-17 11:23:30,487 - pocketoptimizer.scoring.smina_scorer - INFO - Ligand-Sidechain interaction energy for residue: A_376_TRP already computed.
2023-10-17 11:23:30,487 - pocketoptimizer.scoring.smina_scorer - INFO - Ligand-Sidechain interaction energy for residue: A_376_TYR already computed.
2023-10-17 11:23:30,487 - pocketoptimizer.scoring.smina_scorer - INFO - Ligand-Sidechain interaction energy for residue: A_376_VAL already computed.
2023-10-17 11:23:30,487 - pocketoptimizer.scoring.smina_scorer - INFO - Ligand scoring was successful.
2023-10-17 11:23:30,488 - pocketoptimizer.ui - INFO - Energy calculation was successful.
2023-10-17 11:24:20,772 - pocketoptimizer.solving.sontag_solver - INFO - Calculating Solutions.
Solutions:  40%|███████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                                        | 4/10 [01:26<02:23, 23.93s/it]2023-10-17 11:28:23,464 - pocketoptimizer.solving.sontag_solver - ERROR - Sontag solver failed with the following exception: terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
.
Solutions:  40%|███████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                                        | 4/10 [04:02<06:03, 60.65s/it]
Traceback (most recent call last):
  File "/media/Data1/Softwares/pocketoptimizer/pocketoptimizer/ui.py", line 878, in <module>
    main()
  File "/media/Data1/Softwares/pocketoptimizer/pocketoptimizer/ui.py", line 873, in main
    design.design(num_solutions=args.num_solutions,
  File "/media/Data1/Softwares/pocketoptimizer/pocketoptimizer/ui.py", line 617, in design
    sontag_solver.calculate_design_solutions(solver_bin=self.solver,
  File "/media/Data1/Softwares/pocketoptimizer/pocketoptimizer/solving/sontag_solver.py", line 181, in calculate_design_solutions
    run_sontag_solver(
  File "/media/Data1/Softwares/pocketoptimizer/pocketoptimizer/solving/sontag_solver.py", line 55, in run_sontag_solver
    raise RuntimeError(f'Sontag solver failed with the following exception: {stderr.decode("ascii")}.')
RuntimeError: Sontag solver failed with the following exception: terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

OR

```
python /media/Data1/Softwares/pocketoptimizer/pocketoptimizer/ui.py -ff charmm36 -r receptor.pdb -l ligand.mol2 --ph 7 --min_bb --mutations A:111:ALL A:113:ALL A:132:ALL A:344:ALL A:374:ALL A:376:ALL --library dunbrack --accurate --include_native --nconfs 200 --trans 5 --scoring vina --ncpus 8 --num_solutions 10
.
.
.
2023-10-17 10:00:11,738 - pocketoptimizer.solving.sontag_solver - ERROR - Sontag solver failed with the following exception: . 
```
These errors appear when I run the command to design some positions but the program runs fine if I include or ignore others. 
Any idea how to solve this problem?

Thanks in advance.

**Comment by jnoske** [comment]
Hi almeida85,

If you include to many design positions or you want to design to many residues at positions then it could be that the sontag solver runs out of memory. In these cases every other part of the program would run fine but the final solving step may fail. Here the only solution is to lower the size of the design space, by excluding positions, residues or sampling less rotamers/ligand poses. Maybe you can monitor the RAM during the solving procedure and see if this is the problem here?

Best,
Jakob
